name: (Saucedemo) Run test
on: [workflow_dispatch]
jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./saucedemo-university
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5
      - name: Move to saucedemo project folder
        run: cd cypress-cucumber-setup
      - name: Install project dependencies
        run: npm install
      - name: Run cypress tests
        run: npx cypress run
